# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reax',
                'doc_host': 'https://fredguth.github.io',
                'git_url': 'https://github.com/fredguth/reax',
                'lib_path': 'reax'},
  'syms': {'reax.core': {'reax.core.foo': ('core.html#foo', 'reax/core.py')}}}
