# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_core.ipynb 3
from collections import defaultdict
from functools import partial
from itertools import zip_longest
from operator import itemgetter
from typing import Callable, NamedTuple, Tuple, Any, Optional, Union, TypeVar, Sequence, Mapping, List, Tuple, Dict, Hashable, Iterable, Type, cast, overload

import haiku as hk
import jax
import jax.numpy as jnp
import lovely_jax as lj
import lovely_tensors as lt
import numpy as np
import optax
import torchvision
import torchvision.transforms as transforms
from lovely_numpy import lo as ln
# from ./stores import Writable
from torch.utils.data import DataLoader, default_collate
import torch
